# Generated by Django 3.0 on 2019-12-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sighting',
            new_name='Sightings',
        ),
    ]
